### ISSUE TITLE
ArgumentError - Illformed requirement `"~> v1.0.0-alpha.1"`

### ISSUE THREAD

**Issue by angelos3lex** [mapbox/mapbox-directions-swift#421]
I need to install the v1.0.0 version, and in my pod file I do it like:
     
      pod 'MapboxDirections', '~> v1.0.0-alpha.1'
Though, when I try pod install, I get the error:

```
ArgumentError - Illformed requirement `"~> v1.0.0-alpha.1"`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/dependency.rb:101:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:949:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:949:in `block in pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:945:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:945:in `pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:44:in `block in from_podfile'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `from_podfile'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:85:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:416:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:416:in `create_analyzer'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:227:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

Tried using Cocoapods version 1.8.4

**Comment by 1ec5** [comment]
Sorry, that was a typo. The `v` is unnecessary. The readme has been updated.

Incidentally, we’re about to release v0.40.0 with all the changes that were in v1.0.0-alpha.1 and more. We’re going to resume working on v1.0.0 after that.
